# Generated by Django 3.0.4 on 2020-03-08 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='customerdetails',
            name='added_on',
        ),
        migrations.AddField(
            model_name='appdownload',
            name='created_by',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='appdownload',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='appdownload',
            name='updated_by',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='appdownload',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='created_by',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='updated_by',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='created_by',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='last_updated_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='updated_by',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='election',
            name='created_by',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='election',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='updated_by',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='election',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='extendeddata',
            name='last_updated_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='voterdetails',
            name='last_updated_by',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='voterdetails',
            name='last_updated_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
