# Generated by Django 3.0.4 on 2020-03-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_auto_20200308_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterdetails',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='assembly_no',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='booth_eng',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='booth_hin',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='contact_no',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='house_no_eng',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='house_no_hin',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='part_no',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='relation_type',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('husband', 'Husband'), ('orphan', 'Orphan')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='relative_name_eng',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='relative_name_hin',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='section_eng',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='section_hin',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='serial_no',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='support_no',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='voter_id_card_no',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='voter_name_eng',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='voter_name_hin',
            field=models.TextField(blank=True),
        ),
    ]
