# Generated by Django 3.0.4 on 2020-03-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0003_auto_20200309_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterdetails',
            name='contact_no',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='support_no',
            field=models.TextField(blank=True),
        ),
    ]
